### ISSUE TITLE
rjd3highfreq and rjd3toolkit

### ISSUE THREAD

**Issue by AQLT** [palatej/rjd3highfreq#3]
When loading rjd3highfreq before rjd3x13 it seems to create some conflicts:
``` r
library(rjd3highfreq)
library(rjd3x13)
sa2 = jx13(rjd3toolkit::ABS$X0.2.09.10.M)
head(rjd3toolkit::dictionary(sa2))
#> Error in .jcall(jiter, "Ljava/lang/Object;", "next"): java.util.NoSuchElementException
```

``` r
library(rjd3x13)
library(rjd3highfreq)
sa2 = jx13(rjd3toolkit::ABS$X0.2.09.10.M)
head(rjd3toolkit::dictionary(sa2))
#> [1] "preadjustment.a1"  "preadjustment.a1a" "preadjustment.a1b"
#> [4] "preadjustment.a6"  "preadjustment.a7"  "preadjustment.a8"
```

**Comment by palatej** [comment]
It's not a conflict, but a problem in the creation of the dictionaries in Java, which should be done when all the packages are loaded. I will add code to refresh automatically the dictionaries when a new package is loaded and a function to reload "manually" the dictionaries (in case of). Available in v0.4.1
